package contentrepo

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)

var githubAPIBase = "https://api.github.com"

type GitHubPublisher struct {
	httpClient *http.Client
	token      string
	repo       string
	baseBranch string
	reviewer   string
}

type PublishResult struct {
	PullRequestURL string
	Branch         string
	FilePath       string
}

type githubRepoResponse struct {
	DefaultBranch string `json:"default_branch"`
}

type githubRefResponse struct {
	Object struct {
		SHA string `json:"sha"`
	} `json:"object"`
}

type githubContentResponse struct {
	SHA      string `json:"sha"`
	Content  string `json:"content"`
	Encoding string `json:"encoding"`
}

type githubPRResponse struct {
	HTMLURL string `json:"html_url"`
}

func NewGitHubPublisher(token string, repo string, baseBranch string, reviewer string) *GitHubPublisher {
	return &GitHubPublisher{
		httpClient: &http.Client{Timeout: 30 * time.Second},
		token:      strings.TrimSpace(token),
		repo:       strings.TrimSpace(repo),
		baseBranch: strings.TrimSpace(baseBranch),
		reviewer:   strings.Trim(strings.TrimSpace(reviewer), "@"),
	}
}

func (publisher *GitHubPublisher) Publish(ctx context.Context, post BlogPost, sourceReportPath string) (PublishResult, error) {
	if publisher.token == "" {
		return PublishResult{}, fmt.Errorf("github token is required")
	}
	owner, repo, err := splitRepo(publisher.repo)
	if err != nil {
		return PublishResult{}, err
	}

	baseBranch := publisher.baseBranch
	if baseBranch == "" {
		baseBranch, err = publisher.fetchDefaultBranch(ctx, owner, repo)
		if err != nil {
			return PublishResult{}, err
		}
	}
	if err := publisher.validateReadmeContract(ctx, owner, repo, baseBranch); err != nil {
		return PublishResult{}, err
	}

	path := post.FilePath()
	if sha, err := publisher.fetchContentSHA(ctx, owner, repo, path, baseBranch); err != nil {
		return PublishResult{}, err
	} else if sha != "" {
		return PublishResult{}, fmt.Errorf("content file already exists on %s: %s", baseBranch, path)
	}

	baseSHA, err := publisher.fetchBranchSHA(ctx, owner, repo, baseBranch)
	if err != nil {
		return PublishResult{}, err
	}

	branch := fmt.Sprintf("seo/content/%s-%s", post.Slug, time.Now().UTC().Format("20060102-150405"))
	if err := publisher.createBranch(ctx, owner, repo, branch, baseSHA); err != nil {
		return PublishResult{}, err
	}

	if err := publisher.putContent(ctx, owner, repo, path, branch, "", post.Markdown(), "add blog: "+post.Slug); err != nil {
		return PublishResult{}, err
	}

	prURL, err := publisher.createPullRequest(ctx, owner, repo, baseBranch, branch, post, sourceReportPath)
	if err != nil {
		return PublishResult{}, err
	}

	return PublishResult{PullRequestURL: prURL, Branch: branch, FilePath: path}, nil
}

func (publisher *GitHubPublisher) validateReadmeContract(ctx context.Context, owner string, repo string, branch string) error {
	readme, err := publisher.fetchContent(ctx, owner, repo, "README.md", branch)
	if err != nil {
		return fmt.Errorf("read content repo README.md: %w", err)
	}
	required := []string{
		"blogs/",
		"title:",
		"slug:",
		"description:",
		"author:",
		"read_time:",
		"cover:",
		"published_at:",
		"destination",
	}
	for _, needle := range required {
		if !strings.Contains(readme, needle) {
			return fmt.Errorf("content repo README.md missing expected blog contract marker %q", needle)
		}
	}
	return nil
}

func (publisher *GitHubPublisher) createPullRequest(ctx context.Context, owner string, repo string, baseBranch string, headBranch string, post BlogPost, sourceReportPath string) (string, error) {
	body := []string{
		coverReviewerLine(publisher.reviewer),
		"",
		"Automated CreateOS SEO draft generated by the competitor workflow.",
		"",
		"Review checklist:",
		"- Add or replace the cover image before merge.",
		"- Validate product claims and brand voice.",
		"- Confirm internal links are intentional.",
		"- Team can merge when content and cover are ready; content repo deploy hooks will publish after merge.",
		"",
		"Content file:",
		"- `" + post.FilePath() + "`",
		"",
		"Metadata:",
		"- Slug: `" + post.Slug + "`",
		"- Destination: `" + post.Destination + "`",
		"- Published at: `" + post.PublishedAt.UTC().Format(time.RFC3339) + "`",
	}
	if strings.TrimSpace(sourceReportPath) != "" {
		body = append(body, "- Source report: `"+strings.TrimSpace(sourceReportPath)+"`")
	}

	payload := map[string]any{
		"title": "Add CreateOS SEO blog: " + post.Title,
		"head":  headBranch,
		"base":  baseBranch,
		"body":  strings.Join(body, "\n"),
	}

	var parsed githubPRResponse
	if err := publisher.requestJSON(ctx, http.MethodPost, fmt.Sprintf("%s/repos/%s/%s/pulls", githubAPIBase, owner, repo), payload, &parsed); err != nil {
		return "", fmt.Errorf("create pull request: %w", err)
	}
	if parsed.HTMLURL == "" {
		return "", fmt.Errorf("create pull request returned empty html_url")
	}
	return parsed.HTMLURL, nil
}

func coverReviewerLine(reviewer string) string {
	if strings.TrimSpace(reviewer) == "" {
		return "Cover image requested."
	}
	return "@" + strings.Trim(reviewer, "@") + " please create the cover image for this blog and take the next action on Multica."
}

func splitRepo(repo string) (string, string, error) {
	parts := strings.Split(strings.TrimSpace(repo), "/")
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		return "", "", fmt.Errorf("invalid content repo %q, expected owner/repo", repo)
	}
	return parts[0], parts[1], nil
}

func (publisher *GitHubPublisher) fetchDefaultBranch(ctx context.Context, owner string, repo string) (string, error) {
	var parsed githubRepoResponse
	if err := publisher.requestJSON(ctx, http.MethodGet, fmt.Sprintf("%s/repos/%s/%s", githubAPIBase, owner, repo), nil, &parsed); err != nil {
		return "", fmt.Errorf("fetch default branch: %w", err)
	}
	if parsed.DefaultBranch == "" {
		return "", fmt.Errorf("repository %s/%s returned empty default branch", owner, repo)
	}
	return parsed.DefaultBranch, nil
}

func (publisher *GitHubPublisher) fetchBranchSHA(ctx context.Context, owner string, repo string, branch string) (string, error) {
	var parsed githubRefResponse
	if err := publisher.requestJSON(ctx, http.MethodGet, fmt.Sprintf("%s/repos/%s/%s/git/ref/heads/%s", githubAPIBase, owner, repo, url.PathEscape(branch)), nil, &parsed); err != nil {
		return "", fmt.Errorf("fetch branch sha for %q: %w", branch, err)
	}
	if parsed.Object.SHA == "" {
		return "", fmt.Errorf("branch %q has empty sha", branch)
	}
	return parsed.Object.SHA, nil
}

func (publisher *GitHubPublisher) createBranch(ctx context.Context, owner string, repo string, branch string, sha string) error {
	payload := map[string]any{"ref": "refs/heads/" + branch, "sha": sha}
	if err := publisher.requestJSON(ctx, http.MethodPost, fmt.Sprintf("%s/repos/%s/%s/git/refs", githubAPIBase, owner, repo), payload, nil); err != nil {
		return fmt.Errorf("create branch %q: %w", branch, err)
	}
	return nil
}

func (publisher *GitHubPublisher) fetchContentSHA(ctx context.Context, owner string, repo string, path string, branch string) (string, error) {
	requestURL := fmt.Sprintf("%s/repos/%s/%s/contents/%s?ref=%s", githubAPIBase, owner, repo, path, url.QueryEscape(branch))
	var parsed githubContentResponse
	if err := publisher.requestJSON(ctx, http.MethodGet, requestURL, nil, &parsed); err != nil {
		if strings.Contains(err.Error(), "status=404") {
			return "", nil
		}
		return "", fmt.Errorf("fetch content sha: %w", err)
	}
	return parsed.SHA, nil
}

func (publisher *GitHubPublisher) fetchContent(ctx context.Context, owner string, repo string, path string, branch string) (string, error) {
	requestURL := fmt.Sprintf("%s/repos/%s/%s/contents/%s?ref=%s", githubAPIBase, owner, repo, path, url.QueryEscape(branch))
	var parsed githubContentResponse
	if err := publisher.requestJSON(ctx, http.MethodGet, requestURL, nil, &parsed); err != nil {
		return "", fmt.Errorf("fetch content: %w", err)
	}
	if parsed.Encoding != "base64" {
		return "", fmt.Errorf("unsupported content encoding %q", parsed.Encoding)
	}
	content, err := base64.StdEncoding.DecodeString(strings.ReplaceAll(parsed.Content, "\n", ""))
	if err != nil {
		return "", fmt.Errorf("decode content: %w", err)
	}
	return string(content), nil
}

func (publisher *GitHubPublisher) putContent(ctx context.Context, owner string, repo string, path string, branch string, sha string, content string, message string) error {
	payload := map[string]any{
		"message": message,
		"content": base64.StdEncoding.EncodeToString([]byte(content)),
		"branch":  branch,
	}
	if sha != "" {
		payload["sha"] = sha
	}
	if err := publisher.requestJSON(ctx, http.MethodPut, fmt.Sprintf("%s/repos/%s/%s/contents/%s", githubAPIBase, owner, repo, path), payload, nil); err != nil {
		return fmt.Errorf("put content file: %w", err)
	}
	return nil
}

func (publisher *GitHubPublisher) requestJSON(ctx context.Context, method string, requestURL string, payload any, out any) error {
	var body io.Reader
	if payload != nil {
		encoded, err := json.Marshal(payload)
		if err != nil {
			return fmt.Errorf("marshal payload: %w", err)
		}
		body = bytes.NewReader(encoded)
	}

	request, err := http.NewRequestWithContext(ctx, method, requestURL, body)
	if err != nil {
		return fmt.Errorf("build request: %w", err)
	}
	request.Header.Set("Accept", "application/vnd.github+json")
	request.Header.Set("X-GitHub-Api-Version", "2022-11-28")
	request.Header.Set("Authorization", "Bearer "+publisher.token)
	if payload != nil {
		request.Header.Set("Content-Type", "application/json")
	}

	response, err := publisher.httpClient.Do(request)
	if err != nil {
		return fmt.Errorf("request failed: %w", err)
	}
	defer response.Body.Close()

	if response.StatusCode < 200 || response.StatusCode >= 300 {
		responseBody, _ := io.ReadAll(io.LimitReader(response.Body, 4096))
		return fmt.Errorf("status=%d body=%q", response.StatusCode, strings.TrimSpace(string(responseBody)))
	}

	if out == nil {
		io.Copy(io.Discard, response.Body)
		return nil
	}
	if err := json.NewDecoder(response.Body).Decode(out); err != nil {
		return fmt.Errorf("decode response: %w", err)
	}
	return nil
}
