package contentrepo

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)

var githubAPIBase = "https://api.github.com"

type GitHubPublisher struct {
	httpClient *http.Client
	token      string
	repo       string
	baseBranch string
	reviewers  []string
}

type PublishResult struct {
	PullRequestURL string
	Branch         string
	FilePath       string
	Warnings       []string
}

type githubRepoResponse struct {
	DefaultBranch string `json:"default_branch"`
}

type githubRefResponse struct {
	Object struct {
		SHA string `json:"sha"`
	} `json:"object"`
}

type githubContentResponse struct {
	SHA      string `json:"sha"`
	Content  string `json:"content"`
	Encoding string `json:"encoding"`
}

type githubPRResponse struct {
	HTMLURL string `json:"html_url"`
	Number  int    `json:"number"`
}

func NewGitHubPublisher(token string, repo string, baseBranch string, reviewer string) *GitHubPublisher {
	return &GitHubPublisher{
		httpClient: &http.Client{Timeout: 30 * time.Second},
		token:      strings.TrimSpace(token),
		repo:       strings.TrimSpace(repo),
		baseBranch: strings.TrimSpace(baseBranch),
		reviewers:  splitHandles(reviewer),
	}
}

type CoverAsset struct {
	Path    string
	Content []byte
}

func (publisher *GitHubPublisher) Publish(ctx context.Context, post BlogPost, sourceReportPath string, assets ...CoverAsset) (PublishResult, error) {
	if publisher.token == "" {
		return PublishResult{}, fmt.Errorf("github token is required")
	}
	owner, repo, err := splitRepo(publisher.repo)
	if err != nil {
		return PublishResult{}, err
	}

	baseBranch := publisher.baseBranch
	if baseBranch == "" {
		baseBranch, err = publisher.fetchDefaultBranch(ctx, owner, repo)
		if err != nil {
			return PublishResult{}, err
		}
	}
	if err := publisher.validateReadmeContract(ctx, owner, repo, baseBranch); err != nil {
		return PublishResult{}, err
	}

	path := post.FilePath()
	if sha, err := publisher.fetchContentSHA(ctx, owner, repo, path, baseBranch); err != nil {
		return PublishResult{}, err
	} else if sha != "" {
		return PublishResult{}, fmt.Errorf("content file already exists on %s: %s", baseBranch, path)
	}

	baseSHA, err := publisher.fetchBranchSHA(ctx, owner, repo, baseBranch)
	if err != nil {
		return PublishResult{}, err
	}

	branch := fmt.Sprintf("seo/content/%s-%s", post.Slug, time.Now().UTC().Format("20060102-150405"))
	if err := publisher.createBranch(ctx, owner, repo, branch, baseSHA); err != nil {
		return PublishResult{}, err
	}

	for _, asset := range assets {
		assetPath := strings.TrimSpace(asset.Path)
		if assetPath == "" || len(asset.Content) == 0 {
			continue
		}
		if err := publisher.putContentBytes(ctx, owner, repo, assetPath, branch, "", asset.Content, "add cover: "+post.Slug); err != nil {
			return PublishResult{}, err
		}
	}

	if err := publisher.putContent(ctx, owner, repo, path, branch, "", post.Markdown(), "add blog: "+post.Slug); err != nil {
		return PublishResult{}, err
	}

	pr, err := publisher.createPullRequest(ctx, owner, repo, baseBranch, branch, post, sourceReportPath)
	if err != nil {
		return PublishResult{}, err
	}
	warnings := publisher.completeReviewHandoff(ctx, owner, repo, pr.Number, post)

	return PublishResult{PullRequestURL: pr.HTMLURL, Branch: branch, FilePath: path, Warnings: warnings}, nil
}

func (publisher *GitHubPublisher) validateReadmeContract(ctx context.Context, owner string, repo string, branch string) error {
	readme, err := publisher.fetchContent(ctx, owner, repo, "README.md", branch)
	if err != nil {
		return fmt.Errorf("read content repo README.md: %w", err)
	}
	required := []string{
		"blogs/",
		"title:",
		"slug:",
		"description:",
		"author:",
		"read_time:",
		"cover:",
		"published_at:",
		"destination",
	}
	for _, needle := range required {
		if !strings.Contains(readme, needle) {
			return fmt.Errorf("content repo README.md missing expected blog contract marker %q", needle)
		}
	}
	return nil
}

func (publisher *GitHubPublisher) createPullRequest(ctx context.Context, owner string, repo string, baseBranch string, headBranch string, post BlogPost, sourceReportPath string) (githubPRResponse, error) {
	body := []string{
		approvalReviewerLine(publisher.reviewers),
		"",
		"Automated CreateOS SEO draft generated by the competitor workflow.",
		"",
		"Review checklist:",
		"- Validate the generated cover image before merge.",
		"- Validate product claims and brand voice.",
		"- Confirm internal links are intentional.",
		"- Team can merge when approval is complete; content repo deploy hooks will publish after merge.",
		"",
		"Content file:",
		"- `" + post.FilePath() + "`",
		"",
		"Metadata:",
		"- Slug: `" + post.Slug + "`",
		"- Destination: `" + post.Destination + "`",
		"- Published at: `" + post.PublishedAt.UTC().Format(time.RFC3339) + "`",
	}
	if strings.TrimSpace(sourceReportPath) != "" {
		body = append(body, "- Source report: `"+strings.TrimSpace(sourceReportPath)+"`")
	}

	payload := map[string]any{
		"title": "Add CreateOS SEO blog: " + post.Title,
		"head":  headBranch,
		"base":  baseBranch,
		"body":  strings.Join(body, "\n"),
	}

	var parsed githubPRResponse
	if err := publisher.requestJSON(ctx, http.MethodPost, fmt.Sprintf("%s/repos/%s/%s/pulls", githubAPIBase, owner, repo), payload, &parsed); err != nil {
		return githubPRResponse{}, fmt.Errorf("create pull request: %w", err)
	}
	if parsed.HTMLURL == "" || parsed.Number == 0 {
		return githubPRResponse{}, fmt.Errorf("create pull request returned incomplete response")
	}
	return parsed, nil
}

func approvalReviewerLine(reviewers []string) string {
	if len(reviewers) == 0 {
		return "Approval requested before merge."
	}
	return handleList(reviewers) + " please review this generated CreateOS blog and approve the next action on Multica."
}

func (publisher *GitHubPublisher) completeReviewHandoff(ctx context.Context, owner string, repo string, prNumber int, post BlogPost) []string {
	warnings := make([]string, 0)
	if prNumber == 0 || len(publisher.reviewers) == 0 {
		return warnings
	}
	if err := publisher.addIssueAssignees(ctx, owner, repo, prNumber, publisher.reviewers); err != nil {
		warnings = append(warnings, fmt.Sprintf("github PR assignment blocked: %v", err))
	}
	if err := publisher.requestPullRequestReviewers(ctx, owner, repo, prNumber, publisher.reviewers); err != nil {
		warnings = append(warnings, fmt.Sprintf("github review request blocked: %v", err))
	}
	return warnings
}

func (publisher *GitHubPublisher) addIssueAssignees(ctx context.Context, owner string, repo string, issueNumber int, assignees []string) error {
	payload := map[string]any{"assignees": assignees}
	if err := publisher.requestJSON(ctx, http.MethodPost, fmt.Sprintf("%s/repos/%s/%s/issues/%d/assignees", githubAPIBase, owner, repo, issueNumber), payload, nil); err != nil {
		return fmt.Errorf("add assignees: %w", err)
	}
	return nil
}

func (publisher *GitHubPublisher) requestPullRequestReviewers(ctx context.Context, owner string, repo string, prNumber int, reviewers []string) error {
	payload := map[string]any{"reviewers": reviewers}
	if err := publisher.requestJSON(ctx, http.MethodPost, fmt.Sprintf("%s/repos/%s/%s/pulls/%d/requested_reviewers", githubAPIBase, owner, repo, prNumber), payload, nil); err != nil {
		return fmt.Errorf("request reviewers: %w", err)
	}
	return nil
}

func splitHandles(raw string) []string {
	parts := strings.FieldsFunc(raw, func(r rune) bool {
		return r == ',' || r == ' ' || r == '\n' || r == '\t'
	})
	out := make([]string, 0, len(parts))
	seen := map[string]struct{}{}
	for _, part := range parts {
		handle := strings.Trim(strings.TrimSpace(part), "@")
		if handle == "" {
			continue
		}
		key := strings.ToLower(handle)
		if _, ok := seen[key]; ok {
			continue
		}
		seen[key] = struct{}{}
		out = append(out, handle)
	}
	return out
}

func handleList(handles []string) string {
	if len(handles) == 0 {
		return ""
	}
	formatted := make([]string, 0, len(handles))
	for _, handle := range handles {
		formatted = append(formatted, "@"+strings.Trim(handle, "@"))
	}
	return strings.Join(formatted, " ")
}

func splitRepo(repo string) (string, string, error) {
	parts := strings.Split(strings.TrimSpace(repo), "/")
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		return "", "", fmt.Errorf("invalid content repo %q, expected owner/repo", repo)
	}
	return parts[0], parts[1], nil
}

func (publisher *GitHubPublisher) fetchDefaultBranch(ctx context.Context, owner string, repo string) (string, error) {
	var parsed githubRepoResponse
	if err := publisher.requestJSON(ctx, http.MethodGet, fmt.Sprintf("%s/repos/%s/%s", githubAPIBase, owner, repo), nil, &parsed); err != nil {
		return "", fmt.Errorf("fetch default branch: %w", err)
	}
	if parsed.DefaultBranch == "" {
		return "", fmt.Errorf("repository %s/%s returned empty default branch", owner, repo)
	}
	return parsed.DefaultBranch, nil
}

func (publisher *GitHubPublisher) fetchBranchSHA(ctx context.Context, owner string, repo string, branch string) (string, error) {
	var parsed githubRefResponse
	if err := publisher.requestJSON(ctx, http.MethodGet, fmt.Sprintf("%s/repos/%s/%s/git/ref/heads/%s", githubAPIBase, owner, repo, url.PathEscape(branch)), nil, &parsed); err != nil {
		return "", fmt.Errorf("fetch branch sha for %q: %w", branch, err)
	}
	if parsed.Object.SHA == "" {
		return "", fmt.Errorf("branch %q has empty sha", branch)
	}
	return parsed.Object.SHA, nil
}

func (publisher *GitHubPublisher) createBranch(ctx context.Context, owner string, repo string, branch string, sha string) error {
	payload := map[string]any{"ref": "refs/heads/" + branch, "sha": sha}
	if err := publisher.requestJSON(ctx, http.MethodPost, fmt.Sprintf("%s/repos/%s/%s/git/refs", githubAPIBase, owner, repo), payload, nil); err != nil {
		return fmt.Errorf("create branch %q: %w", branch, err)
	}
	return nil
}

func (publisher *GitHubPublisher) fetchContentSHA(ctx context.Context, owner string, repo string, path string, branch string) (string, error) {
	requestURL := fmt.Sprintf("%s/repos/%s/%s/contents/%s?ref=%s", githubAPIBase, owner, repo, path, url.QueryEscape(branch))
	var parsed githubContentResponse
	if err := publisher.requestJSON(ctx, http.MethodGet, requestURL, nil, &parsed); err != nil {
		if strings.Contains(err.Error(), "status=404") {
			return "", nil
		}
		return "", fmt.Errorf("fetch content sha: %w", err)
	}
	return parsed.SHA, nil
}

func (publisher *GitHubPublisher) fetchContent(ctx context.Context, owner string, repo string, path string, branch string) (string, error) {
	requestURL := fmt.Sprintf("%s/repos/%s/%s/contents/%s?ref=%s", githubAPIBase, owner, repo, path, url.QueryEscape(branch))
	var parsed githubContentResponse
	if err := publisher.requestJSON(ctx, http.MethodGet, requestURL, nil, &parsed); err != nil {
		return "", fmt.Errorf("fetch content: %w", err)
	}
	if parsed.Encoding != "base64" {
		return "", fmt.Errorf("unsupported content encoding %q", parsed.Encoding)
	}
	content, err := base64.StdEncoding.DecodeString(strings.ReplaceAll(parsed.Content, "\n", ""))
	if err != nil {
		return "", fmt.Errorf("decode content: %w", err)
	}
	return string(content), nil
}

func (publisher *GitHubPublisher) putContent(ctx context.Context, owner string, repo string, path string, branch string, sha string, content string, message string) error {
	return publisher.putContentBytes(ctx, owner, repo, path, branch, sha, []byte(content), message)
}

func (publisher *GitHubPublisher) putContentBytes(ctx context.Context, owner string, repo string, path string, branch string, sha string, content []byte, message string) error {
	payload := map[string]any{
		"message": message,
		"content": base64.StdEncoding.EncodeToString(content),
		"branch":  branch,
	}
	if sha != "" {
		payload["sha"] = sha
	}
	if err := publisher.requestJSON(ctx, http.MethodPut, fmt.Sprintf("%s/repos/%s/%s/contents/%s", githubAPIBase, owner, repo, path), payload, nil); err != nil {
		return fmt.Errorf("put content file: %w", err)
	}
	return nil
}

func (publisher *GitHubPublisher) requestJSON(ctx context.Context, method string, requestURL string, payload any, out any) error {
	var body io.Reader
	if payload != nil {
		encoded, err := json.Marshal(payload)
		if err != nil {
			return fmt.Errorf("marshal payload: %w", err)
		}
		body = bytes.NewReader(encoded)
	}

	request, err := http.NewRequestWithContext(ctx, method, requestURL, body)
	if err != nil {
		return fmt.Errorf("build request: %w", err)
	}
	request.Header.Set("Accept", "application/vnd.github+json")
	request.Header.Set("X-GitHub-Api-Version", "2022-11-28")
	request.Header.Set("Authorization", "Bearer "+publisher.token)
	if payload != nil {
		request.Header.Set("Content-Type", "application/json")
	}

	response, err := publisher.httpClient.Do(request)
	if err != nil {
		return fmt.Errorf("request failed: %w", err)
	}
	defer response.Body.Close()

	if response.StatusCode < 200 || response.StatusCode >= 300 {
		responseBody, _ := io.ReadAll(io.LimitReader(response.Body, 4096))
		return fmt.Errorf("status=%d body=%q", response.StatusCode, strings.TrimSpace(string(responseBody)))
	}

	if out == nil {
		io.Copy(io.Discard, response.Body)
		return nil
	}
	if err := json.NewDecoder(response.Body).Decode(out); err != nil {
		return fmt.Errorf("decode response: %w", err)
	}
	return nil
}
